spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sales_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok}
    username: ${DB_USERNAME:sales_user}
    password: ${DB_PASSWORD:sales_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: false
